import Head from 'next/head';
import Fullscroll from '../components/fullscrool';
import Nav from "../components/navs/nav"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      <Nav/>
      <Fullscroll/>
    </>
  )
}
